//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap(Locale.init) ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)
  
  static func validate() throws {
    try intern.validate()
  }
  
  /// This `R.file` struct is generated, and contains static references to 26 files.
  struct file {
    /// Resource file `Amour_tojours.mid`.
    static let amour_tojoursMid = Rswift.FileResource(bundle: R.hostingBundle, name: "Amour_tojours", pathExtension: "mid")
    /// Resource file `Avicii_-_Heaven_Chris_Martin.mid`.
    static let avicii__Heaven_Chris_MartinMid = Rswift.FileResource(bundle: R.hostingBundle, name: "Avicii_-_Heaven_Chris_Martin", pathExtension: "mid")
    /// Resource file `Avicii_-_Lonely_Together_ft._Rita_Ora.mid`.
    static let avicii__Lonely_Together_ft_Rita_OraMid = Rswift.FileResource(bundle: R.hostingBundle, name: "Avicii_-_Lonely_Together_ft._Rita_Ora", pathExtension: "mid")
    /// Resource file `Avicii_-_SOS.mid`.
    static let avicii__SOSMid = Rswift.FileResource(bundle: R.hostingBundle, name: "Avicii_-_SOS", pathExtension: "mid")
    /// Resource file `Avicii_-_Without_You_feat._Sandro_Cavazza.mid`.
    static let avicii__Without_You_feat_Sandro_CavazzaMid = Rswift.FileResource(bundle: R.hostingBundle, name: "Avicii_-_Without_You_feat._Sandro_Cavazza", pathExtension: "mid")
    /// Resource file `Avicii_Medley.mid`.
    static let avicii_MedleyMid = Rswift.FileResource(bundle: R.hostingBundle, name: "Avicii_Medley", pathExtension: "mid")
    /// Resource file `Avicii_levels.mid`.
    static let avicii_levelsMid = Rswift.FileResource(bundle: R.hostingBundle, name: "Avicii_levels", pathExtension: "mid")
    /// Resource file `Axwell_L_Ingrosso_-_More_Than_You_Know.mid`.
    static let axwell_L_Ingrosso__More_Than_You_KnowMid = Rswift.FileResource(bundle: R.hostingBundle, name: "Axwell_L_Ingrosso_-_More_Than_You_Know", pathExtension: "mid")
    /// Resource file `Axwell__Ingrosso_-_Dreamer_ft-2.mid`.
    static let axwell__Ingrosso__Dreamer_ft2Mid = Rswift.FileResource(bundle: R.hostingBundle, name: "Axwell__Ingrosso_-_Dreamer_ft-2", pathExtension: "mid")
    /// Resource file `Axwell__Ingrosso_-_Dreamer_ft.mid`.
    static let axwell__Ingrosso__Dreamer_ftMid = Rswift.FileResource(bundle: R.hostingBundle, name: "Axwell__Ingrosso_-_Dreamer_ft", pathExtension: "mid")
    /// Resource file `Belong.mid`.
    static let belongMid = Rswift.FileResource(bundle: R.hostingBundle, name: "Belong", pathExtension: "mid")
    /// Resource file `Calling.mid`.
    static let callingMid = Rswift.FileResource(bundle: R.hostingBundle, name: "Calling", pathExtension: "mid")
    /// Resource file `Heaven_-_Avicii__Piano_Tutorial.mid`.
    static let heaven__Avicii__Piano_TutorialMid = Rswift.FileResource(bundle: R.hostingBundle, name: "Heaven_-_Avicii__Piano_Tutorial", pathExtension: "mid")
    /// Resource file `Heroes_-Alesso_for_Front_ensemble.mid`.
    static let heroes_Alesso_for_Front_ensembleMid = Rswift.FileResource(bundle: R.hostingBundle, name: "Heroes_-Alesso_for_Front_ensemble", pathExtension: "mid")
    /// Resource file `Lonely_together.mid`.
    static let lonely_togetherMid = Rswift.FileResource(bundle: R.hostingBundle, name: "Lonely_together", pathExtension: "mid")
    /// Resource file `More_than_you_know.mid`.
    static let more_than_you_knowMid = Rswift.FileResource(bundle: R.hostingBundle, name: "More_than_you_know", pathExtension: "mid")
    /// Resource file `On_My_Way_-_AxwellIngrosso.mid`.
    static let on_My_Way__AxwellIngrossoMid = Rswift.FileResource(bundle: R.hostingBundle, name: "On_My_Way_-_AxwellIngrosso", pathExtension: "mid")
    /// Resource file `SOS_-_Avicii__Aloe_Blacc.mid`.
    static let sos__Avicii__Aloe_BlaccMid = Rswift.FileResource(bundle: R.hostingBundle, name: "SOS_-_Avicii__Aloe_Blacc", pathExtension: "mid")
    /// Resource file `Sebastian_Ingrosso_-_Reload.mid`.
    static let sebastian_Ingrosso__ReloadMid = Rswift.FileResource(bundle: R.hostingBundle, name: "Sebastian_Ingrosso_-_Reload", pathExtension: "mid")
    /// Resource file `Secrets.mid`.
    static let secretsMid = Rswift.FileResource(bundle: R.hostingBundle, name: "Secrets", pathExtension: "mid")
    /// Resource file `Sun_Is_Shining.mid`.
    static let sun_Is_ShiningMid = Rswift.FileResource(bundle: R.hostingBundle, name: "Sun_Is_Shining", pathExtension: "mid")
    /// Resource file `Swedish_House_Mafia_Medley.mid`.
    static let swedish_House_Mafia_MedleyMid = Rswift.FileResource(bundle: R.hostingBundle, name: "Swedish_House_Mafia_Medley", pathExtension: "mid")
    /// Resource file `Wake_Me_Up_-_Avicii.mid`.
    static let wake_Me_Up__AviciiMid = Rswift.FileResource(bundle: R.hostingBundle, name: "Wake_Me_Up_-_Avicii", pathExtension: "mid")
    /// Resource file `Wake_Me_Up_Avicii.mid`.
    static let wake_Me_Up_AviciiMid = Rswift.FileResource(bundle: R.hostingBundle, name: "Wake_Me_Up_Avicii", pathExtension: "mid")
    /// Resource file `Wake_me_up_Avicii-2.mid`.
    static let wake_me_up_Avicii2Mid = Rswift.FileResource(bundle: R.hostingBundle, name: "Wake_me_up_Avicii-2", pathExtension: "mid")
    /// Resource file `Years.mid`.
    static let yearsMid = Rswift.FileResource(bundle: R.hostingBundle, name: "Years", pathExtension: "mid")
    
    /// `bundle.url(forResource: "Amour_tojours", withExtension: "mid")`
    static func amour_tojoursMid(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.amour_tojoursMid
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "Avicii_-_Heaven_Chris_Martin", withExtension: "mid")`
    static func avicii__Heaven_Chris_MartinMid(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.avicii__Heaven_Chris_MartinMid
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "Avicii_-_Lonely_Together_ft._Rita_Ora", withExtension: "mid")`
    static func avicii__Lonely_Together_ft_Rita_OraMid(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.avicii__Lonely_Together_ft_Rita_OraMid
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "Avicii_-_SOS", withExtension: "mid")`
    static func avicii__SOSMid(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.avicii__SOSMid
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "Avicii_-_Without_You_feat._Sandro_Cavazza", withExtension: "mid")`
    static func avicii__Without_You_feat_Sandro_CavazzaMid(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.avicii__Without_You_feat_Sandro_CavazzaMid
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "Avicii_Medley", withExtension: "mid")`
    static func avicii_MedleyMid(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.avicii_MedleyMid
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "Avicii_levels", withExtension: "mid")`
    static func avicii_levelsMid(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.avicii_levelsMid
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "Axwell_L_Ingrosso_-_More_Than_You_Know", withExtension: "mid")`
    static func axwell_L_Ingrosso__More_Than_You_KnowMid(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.axwell_L_Ingrosso__More_Than_You_KnowMid
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "Axwell__Ingrosso_-_Dreamer_ft", withExtension: "mid")`
    static func axwell__Ingrosso__Dreamer_ftMid(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.axwell__Ingrosso__Dreamer_ftMid
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "Axwell__Ingrosso_-_Dreamer_ft-2", withExtension: "mid")`
    static func axwell__Ingrosso__Dreamer_ft2Mid(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.axwell__Ingrosso__Dreamer_ft2Mid
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "Belong", withExtension: "mid")`
    static func belongMid(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.belongMid
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "Calling", withExtension: "mid")`
    static func callingMid(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.callingMid
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "Heaven_-_Avicii__Piano_Tutorial", withExtension: "mid")`
    static func heaven__Avicii__Piano_TutorialMid(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.heaven__Avicii__Piano_TutorialMid
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "Heroes_-Alesso_for_Front_ensemble", withExtension: "mid")`
    static func heroes_Alesso_for_Front_ensembleMid(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.heroes_Alesso_for_Front_ensembleMid
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "Lonely_together", withExtension: "mid")`
    static func lonely_togetherMid(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.lonely_togetherMid
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "More_than_you_know", withExtension: "mid")`
    static func more_than_you_knowMid(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.more_than_you_knowMid
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "On_My_Way_-_AxwellIngrosso", withExtension: "mid")`
    static func on_My_Way__AxwellIngrossoMid(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.on_My_Way__AxwellIngrossoMid
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "SOS_-_Avicii__Aloe_Blacc", withExtension: "mid")`
    static func sos__Avicii__Aloe_BlaccMid(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.sos__Avicii__Aloe_BlaccMid
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "Sebastian_Ingrosso_-_Reload", withExtension: "mid")`
    static func sebastian_Ingrosso__ReloadMid(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.sebastian_Ingrosso__ReloadMid
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "Secrets", withExtension: "mid")`
    static func secretsMid(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.secretsMid
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "Sun_Is_Shining", withExtension: "mid")`
    static func sun_Is_ShiningMid(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.sun_Is_ShiningMid
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "Swedish_House_Mafia_Medley", withExtension: "mid")`
    static func swedish_House_Mafia_MedleyMid(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.swedish_House_Mafia_MedleyMid
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "Wake_Me_Up_-_Avicii", withExtension: "mid")`
    static func wake_Me_Up__AviciiMid(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.wake_Me_Up__AviciiMid
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "Wake_Me_Up_Avicii", withExtension: "mid")`
    static func wake_Me_Up_AviciiMid(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.wake_Me_Up_AviciiMid
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "Wake_me_up_Avicii-2", withExtension: "mid")`
    static func wake_me_up_Avicii2Mid(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.wake_me_up_Avicii2Mid
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "Years", withExtension: "mid")`
    static func yearsMid(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.yearsMid
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.storyboard` struct is generated, and contains static references to 1 storyboards.
  struct storyboard {
    /// Storyboard `LaunchScreen`.
    static let launchScreen = _R.storyboard.launchScreen()
    
    /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
    static func launchScreen(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.launchScreen)
    }
    
    fileprivate init() {}
  }
  
  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      try _R.validate()
    }
    
    fileprivate init() {}
  }
  
  fileprivate class Class {}
  
  fileprivate init() {}
}

struct _R: Rswift.Validatable {
  static func validate() throws {
    try storyboard.validate()
  }
  
  struct storyboard: Rswift.Validatable {
    static func validate() throws {
      try launchScreen.validate()
    }
    
    struct launchScreen: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UIViewController
      
      let bundle = R.hostingBundle
      let name = "LaunchScreen"
      
      static func validate() throws {
        if #available(iOS 11.0, *) {
        }
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  fileprivate init() {}
}
